name: Execute Flow
on:
  workflow_dispatch:
    inputs:
      work_queue:
        description: 'Work Queue name'
        required: false
        default: 'ga_queue_default'
      image:
        description: 'Docker image name'
        required: false
        default: ''
      run_once:
        description: 'Run once and exit'
        type: boolean
        required: false
        default: false

jobs:
  execute-flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.GHCR_TOKEN_FOR_TIANXA }}
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync

      - name: Pull Docker Image
        if: ${{ inputs.image != '' }}
        run: docker pull ${{ inputs.image }}

      - name: Run Flow in Docker
        env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          PREFECT_API_AUTH_STRING: ${{ secrets.PREFECT_API_AUTH_STRING }}
          PREFECT_WORKER_QUERY_SECONDS: '5'
        run: |
          ARGS=""
          if [ "${{ inputs.run_once }}" == "true" ]; then
            ARGS="--run-once"
          fi
          uv run prefect worker start --pool gdq-etl-pool --limit 1 $ARGS --name "${GITHUB_REPOSITORY//\//-}-$GITHUB_RUN_ID" --work-queue "${{ inputs.work_queue }}" --type docker --install-policy never
